// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IArticleFields {
  /** Картинка */
  image: Asset;

  /** Автор */
  author: string;

  /** Заголовок */
  title: string;

  /** Описание */
  description: string;

  /** slug */
  slug: string;

  /** Tags */
  tag: string;

  /** Текст */
  text: Document;

  /** Дата публикации */
  date: string;
}

export interface IArticle extends Entry<IArticleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "article";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IMainFields {
  /** Title */
  title: string;

  /** Description */
  description?: string | undefined;

  /** Body */
  body?: Document | undefined;

  /** Image */
  image?: Asset | undefined;
}

export interface IMain extends Entry<IMainFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "main";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "article" | "main";

export type IEntry = IArticle | IMain;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
