import { Metadata } from "next";
import Link from "next/link";

export type PostType = {
  id: number;
  title: string,
  userid: number;
  body: string
}

export const metadata: Metadata = {
  title: 'Blog | Next-13 App',
  description: 'Generated by create next app',
}

const getData = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/posts', {
    next: {
      revalidate: 60
    }
  })
  return response.json()
}

const Blog = async () => {
  const posts = await getData()

  return (
    <div className={" px-3"}>
      <h1 className={" my-5 text-3xl  text-center"}>Blog page</h1>

      <ul >
        {posts.map((post: PostType) => (
          <li key={post.id}>
            <Link href={`/blog/${post.id}`} className={" hover:text-orange-500 hover:translate-x-0.5"}>
              {post.title}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  )
}
export default Blog