"use client"

import { useEffect, useState } from "react";
import { getPosts } from "@/service/getData";
import { Posts } from "@/components/Posts";
import { SearchPosts } from "@/components/SearchPosts";

export type PostType = {
  id: number;
  title: string,
  userid: number;
  body: string
}
//
// export const metadata: Metadata = {
//   title: 'Blog | Next-13 App',
//   description: 'Generated by create next app',
// }



const Blog = () => {
  const [posts, setPosts] = useState<PostType[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    getPosts()
      .then(posts => setPosts(posts))
      .finally(() => setLoading(false))
  }, []);

  return (
    <div className={" px-3"}>
      <h1 className={" my-5 text-3xl  text-center"}>Blog page</h1>
      <SearchPosts getSearchPosts={setPosts}/>

      {loading ? <p>Loading...</p> :
       <Posts posts={posts}/>
      }
    </div>
  )
}
export default Blog