import { Posts } from '@/components/posts/Posts';
import { SearchPosts } from '@/components/search-post/SearchPosts';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Blog | Next-13 App',
    // description: 'Generated by create next app',
};

const Blog = () => {
    return (
        <div className={'px-3'}>
            <h1 className={'my-5 text-3xl text-center'}>Blog page</h1>
            <SearchPosts />
            <Posts />
        </div>
    );
};
export default Blog;
