import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Footer, Header } from '@/components';
import './globals.css';
import { Provider } from '@/components/session-provider/Provider';
import Profile from '@/components/profile/Profile';
import cl from 'clsx';
import s from './rootLayout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'HOME | Next-13 App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={cl(inter.className, s.body)}>
                <Provider>
                    <Header>
                        <Profile />
                    </Header>
                    <main className={s.main}>
                        <p className={s.title}>{'THE BLOG'}</p>
                        {children}
                    </main>
                    <Footer />
                </Provider>
            </body>
        </html>
    );
}
