import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Footer, Header } from "@/components";
import './globals.css'

const inter = Inter({ subsets: ['latin']})

export const metadata: Metadata = {
  title: 'HOME | Next-13 App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={`${inter.className} grid grid-rows-[auto_1fr_auto] min-h-screen  `}>
        <Header/>
          <main className={" container mx-auto"}>
            {children}
          </main>
        <Footer/>
      </body>
    </html>
  )
}
