import { Metadata } from 'next';
import { documentToReactComponents } from '@contentful/rich-text-react-renderer';
import { client } from '@/clientContentful/client';
import { IMainFields } from '@/contentful';

// export const metadata: Metadata = {
//     title: 'Home page | Next-14 App',
//     description: 'Generated by create next app',
// };

async function fetchPostData() {
    const data = await client.getEntries({ content_type: 'main' });
    return data.items[0].fields as unknown as IMainFields;
}

export const generateMetadata = async (): Promise<Metadata> => {
    const { title, description } = await fetchPostData();
    return {
        title: `${title} | Next App`,
        description: description,
    };
};

export default async function Post() {
    const data = await fetchPostData();
    const image = data.image?.fields.file?.url;

    return (
        <section>
            <div
                style={{ backgroundImage: `url(http:${image})` }}
                className='bg-cover bg-center h-64 w-full text-white flex flex-col justify-center items-center'
            >
                <h1 className={'text-3xl font-bold sm:text-4xl '}>{data.title}</h1>
                <h2 className={'text-xl'}>{data.description}</h2>
            </div>
            <div className={'py-3 px-2 md:px-1'}>{documentToReactComponents(data.body!)}</div>
        </section>
    );
}

// export async function generateStaticParams() {
//     const ids = ['1', '2', '3']; // Это должны быть ID, которые вы хотите сгенерировать
//     return ids.map(id => ({ id }));
// }
