import { Metadata } from 'next';
import { getPostById, getPosts } from '@/service/getData';

type ParamsType = {
    params: {
        id: string;
    };
};

export const generateMetadata = async ({ params: { id } }: ParamsType): Promise<Metadata> => {
    const { title } = await getPostById(id);
    return {
        title: `${title} | Next-13 App`,
        // description: 'Generated by create next app',
    };
};

const Post = async ({ params: { id } }: ParamsType) => {
    const post = await getPostById(id);

    return (
        <div>
            <h1 className={'text-3xl border-b py-3 text-center'}>{post.title}</h1>
            <p>{post.body}</p>
        </div>
    );
};
export default Post;

export async function generateStaticParams() {
    const posts = await getPosts();
    return posts.map((post: any) => ({
        id: post.id.toString(),
    }));
}
